version: "3.8"

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    build: ./bd
    container_name: postgres_db
    environment:
      POSTGRES_DB: escola
    ports:
      - "3000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_exporter:
    image: bitnami/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://leonardo:leonardo@db:5432/escola"
    ports:
      - "9187:9187"
    depends_on:
      - db
    networks:
      - monitoring_network

volumes:
  postgres_data:

networks:
  monitoring_network:
