version: "3.8"

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    build: ./InfraBD
    container_name: postgres_db
    environment:
      POSTGRES_USER: leonardo
      POSTGRES_PASSWORD: leonardo123
      POSTGRES_DB: escola
    ports:
      - "3000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
