version: "3.8"

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    build: ./bd
    container_name: postgres_db
    environment:
      POSTGRES_USER: leonardo
      POSTGRES_PASSWORD: leonardo123
      POSTGRES_DB: escola
    ports:
      - "3000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_exporter:
    image: quay.io/prometheus/postgres-exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://leonardo:leonardo123@db:5432/escola"
    ports:
      - "9187:9187"
    depends_on:
      - db
    networks:
      - monitoring_network

  prometheus:
    image: prom/prometheus
    build:
      context: ./prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - postgres_exporter

  grafana:
    build:
      context: ./grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring_network

volumes:
  postgres_data:
